#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display, strum::EnumIter)]
pub enum Boss {
    AbyssalSire,
    AlchemicalHydra,
    Artio,
    Amoxliatl,
    Araxxor,
    BarrowsChests,
    Byrophyta,
    Callisto,
    Calvarion,
    Cerberus,
    ChambersOfXeric,
    ChambersOfXericChallengeMode,
    ChaosElemental,
    ChaosFanatic,
    CommanderZilyana,
    CorporealBeast,
    CrazyArchaeologist,
    DagannothPrime,
    DagannothRex,
    DagannothSupreme,
    DerangedArchaeologist,
    DoomOfMokhaiotl,
    DukeSucellus,
    GeneralGraardor,
    GiantMole,
    GrotesqueGuardians,
    Hespori,
    KalphiteQueen,
    KingBlackDragon,
    Kraken,
    Kreearra,
    KrilTsutsaroth,
    LunarChests,
    Mimic,
    Nex,
    Nightmare,
    PhosanisNightmare,
    Obor,
    PhantomMuspah,
    Sarachnis,
    Scorpia,
    Scurrius,
    ShellbaneGryphon,
    Skotizo,
    SolHeredit,
    Spindel,
    Tempoross,
    TheGauntlet,
    TheCorruptedGauntlet,
    TheHueycoatl,
    TheLeviathan,
    TheRoyalTitans,
    TheWhisperer,
    TheatreOfBlood,
    TheatreOfBloodHardMode,
    ThermonuclearSmokeDevil,
    TombsOfAmascut,
    TombsOfAmascutExpertMode,
    TzKalZuk,
    TzTokJad,
    Vardorvis,
    Venenatis,
    Vetion,
    Vorkath,
    Wintertodt,
    Yama,
    Zalcano,
    Zulrah,
}

impl Boss {
    pub fn name(&self) -> &str {
        match self {
            Self::AbyssalSire => "Abyssal Sire",
            Self::AlchemicalHydra => "Alchemical Hydra",
            Self::Amoxliatl => "Amoxliatl",
            Self::Araxxor => "Araxxor",
            Self::Artio => "Artio",
            Self::BarrowsChests => "Barrows Chests",
            Self::Byrophyta => "Byrophyta",
            Self::Callisto => "Callisto",
            Self::Calvarion => "Calvar'ion",
            Self::Cerberus => "Cerberus",
            Self::ChambersOfXeric => "Chambers of Xeric",
            Self::ChambersOfXericChallengeMode => "Chambers of Xeric: Challenge Mode",
            Self::ChaosElemental => "Chaos Elemental",
            Self::ChaosFanatic => "Chaos Fanatic",
            Self::CommanderZilyana => "Commander Zilyana",
            Self::CorporealBeast => "Corporeal Beast",
            Self::CrazyArchaeologist => "Crazy Archaeologist",
            Self::DagannothPrime => "Dagannoth Prime",
            Self::DagannothRex => "Dagannoth Rex",
            Self::DagannothSupreme => "Dagannoth Supreme",
            Self::DerangedArchaeologist => "Deranged Archaeologist",
            Self::DoomOfMokhaiotl => "Doom of Mokhaiotl",
            Self::DukeSucellus => "Duke Sucellus",
            Self::GeneralGraardor => "General Graardor",
            Self::GiantMole => "Giant Mole",
            Self::GrotesqueGuardians => "Grotesque Guardians",
            Self::Hespori => "Hespori",
            Self::KalphiteQueen => "Kalphite Queen",
            Self::KingBlackDragon => "King Black Dragon",
            Self::Kraken => "Kraken",
            Self::Kreearra => "Kree'arra",
            Self::KrilTsutsaroth => "K'ril Tsutsaroth",
            Self::LunarChests => "Lunar Chests",
            Self::Mimic => "Mimic",
            Self::Nex => "Nex",
            Self::Nightmare => "Nightmare",
            Self::PhosanisNightmare => "Phosani's Nightmare",
            Self::Obor => "Obor",
            Self::PhantomMuspah => "Phantom Muspah",
            Self::Sarachnis => "Sarachnis",
            Self::Scorpia => "Scorpia",
            Self::Scurrius => "Scurrius",
            Self::ShellbaneGryphon => "Shellbane Gryphon",
            Self::Skotizo => "Skotizo",
            Self::SolHeredit => "Sol Heredit",
            Self::Spindel => "Spindel",
            Self::Tempoross => "Tempoross",
            Self::TheGauntlet => "The Gauntlet",
            Self::TheCorruptedGauntlet => "The Corrupted Gauntlet",
            Self::TheHueycoatl => "The Hueycoatl",
            Self::TheLeviathan => "The Leviathan",
            Self::TheRoyalTitans => "The Royal Titans",
            Self::TheWhisperer => "The Whisperer",
            Self::TheatreOfBlood => "Theatre of Blood",
            Self::TheatreOfBloodHardMode => "Theatre of Blood: Hard Mode",
            Self::ThermonuclearSmokeDevil => "Thermonuclear Smoke Devil",
            Self::TombsOfAmascut => "Tombs of Amascut",
            Self::TombsOfAmascutExpertMode => "Tombs of Amascut: Expert Mode",
            Self::TzKalZuk => "TzKal-Zuk",
            Self::TzTokJad => "TzTok-Jad",
            Self::Vardorvis => "Vardorvis",
            Self::Venenatis => "Venenatis",
            Self::Vetion => "Vetion",
            Self::Vorkath => "Vorkath",
            Self::Wintertodt => "Wintertodt",
            Self::Yama => "Yama",
            Self::Zalcano => "Zalcano",
            Self::Zulrah => "Zulrah",
        }
    }
}
